import pygame as pg
pg.font.init()

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 500
SCREEN = pg.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))

FPS = 60

BIRD_FALL_SPEED = 1
BIRD_JUMP_HEIGHT = 13

PIPE_SPEED = 3
PIPE_DISTANCE = 150

BACKGROUND_SPEED = 4

TIME_AFTER_DEATH = 1000

FONT_SIZE = 60
GAME_FONT = pg.font.SysFont("Arial", FONT_SIZE)